apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-master
  labels: 
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379



