apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-slv
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
      role: slave
      tier: backend
  template:
    metadata:
      labels:
        app: mysql
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

