apiVersion: v1
kind: Service
metadata:
  name: mysql-master-svc
  labels: 
    app: mysql
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
  selector:
    app: mysql
    role: master
    tier: backend
    
