apiVersion: v1
kind: Service
metadata:
  name: mysql-slave-svc
  labels:
    app: mysql
    role: slave
    tier: backend
spec:
  ports:
  - port: 6379
  type: ClusterIP
  selector:
    app: mysql
    role: slave
    tier: backend
